name: sentiment_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  # Deep Learning
  - tensorflow>=2.15.0
  - keras>=2.15.0
  # Data Processing
  - pandas>=2.0.0
  - numpy>=1.24.0
  # NLP
  - nltk>=3.8.1
  - spacy>=3.7.0
  # Web Scraping
  - beautifulsoup4>=4.12.0
  - selenium>=4.15.0
  - requests>=2.31.0
  # Visualization
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  # Jupyter
  - jupyter>=1.0.0
  - ipykernel>=6.28.0
  # Additional dependencies
  - scikit-learn>=1.3.0
  - tqdm>=4.66.0
  # pip packages
  - pip:
    - transformers>=4.36.0
    - gensim>=4.3.0
